In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
import xgboost as XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV


In [ ]:
#mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
project_path = '/content/drive/MyDrive/NLP/'
 

In [ ]:
df = pd.read_csv(project_path + 'public_data.csv')
df_test = pd.read_csv(project_path + 'input_data.csv') 
########## For people running locally#####
#emails_df2 = pd.read_csv('enron_classification_df.csv') 

In [ ]:
#df = pd.read_csv("public_data.csv")
print(df.info())
print(df.head())


X = df['message']
y = df['label']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(y_train.shape)
print(X_val.shape)
print(y_val.shape)


vectorizer = TfidfVectorizer(min_df=.01, max_df=.8, ngram_range=[1,3], max_features=300, stop_words='english')

pipe = Pipeline([('vec', vectorizer),  ('clf', DecisionTreeClassifier(random_state=223))])

pipe.fit(X_train, y_train)


from sklearn.metrics import confusion_matrix, classification_report

pred_val = pipe.predict(X_val)
print(confusion_matrix(y_val, pred_val))
print(classification_report(y_val, pred_val))


from sklearn.metrics.cluster import adjusted_rand_score, adjusted_mutual_info_score

ari = adjusted_rand_score(y_val, pred_val)
ami = adjusted_mutual_info_score(y_val, pred_val, average_method='arithmetic')

print("ARI: {}".format(ari))
print("AMI: {}".format(ami))


## Kaggle Predictions


#df_test = pd.read_csv('input_data.csv')
df_test.info()
df_test.head()

pred_test = pipe.predict(df_test['message'])

my_submission = pd.DataFrame({'Id': df_test['id'], 'label': pred_test})
print(my_submission.head())

# NOTE: after saving the CSV file, be sure to zip the file before submitting to the competition website!
my_submission.to_csv('answers.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11623 entries, 0 to 11622
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   id       11623 non-null  int64 
 1   message  11623 non-null  object
 2   label    11623 non-null  object
dtypes: int64(1), object(2)
memory usage: 272.5+ KB
None
     id                                    message              label
0  3343    1 \t pesto drizzle over grilled chicken   orderpizzaintent
1  2959    1 \t pesto drizzle over grilled chicken   orderpizzaintent
2   891                             1 agua frescas   orderdrinkintent
3  1638  1 agua frescas and 1 classic caesar salad   ordersaladintent
4   520                  1 bacon smokehouse burger  orderburgerintent
(9298,)
(9298,)
(2325,)
(2325,)
[[ 45   0   0 ...   0   0   0]
 [  0   1   0 ...   0   0   0]
 [  0   0 168 ...   0   0   1]
 ...
 [  0   0   0 ...  75   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   1 ...   0   0   5]]
      

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [ ]:
pip install cleanlab

     |████████████████████████████████| 78 kB 3.8 MB/s 


In [ ]:
X = df['message']

In [ ]:
from copy import deepcopy
from sklearn.linear_model import LogisticRegression
from sklearn.base import BaseEstimator
from sklearn.model_selection import GridSearchCV
from numpy.random import multivariate_normal
import scipy
import warnings
import pytest
import numpy as np
from cleanlab.classification import LearningWithNoisyLabels
from cleanlab.noise_generation import generate_noise_matrix_from_trace
from cleanlab.noise_generation import generate_noisy_labels
from cleanlab.latent_algebra import compute_inv_noise_matrix


In [ ]:
from sklearn.preprocessing import LabelEncoder
def label_encoder(data):
    class_le = LabelEncoder()    
    h = class_le.fit_transform(df['label'].astype(str))
    return h

In [ ]:
class_le = LabelEncoder() 

In [ ]:
y = class_le.fit_transform(df['label'].astype(str))


In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Compute p(true_label=k)
py = np.bincount(y_train) / float(len(y_train))

noise_matrix = generate_noise_matrix_from_trace(
    37,
    trace=0.9*37,
    py=py,
    valid_noise_matrix=True,
    seed=42,
)

# Generate our noisy labels using the noise_matrix.
s = generate_noisy_labels(y_train, noise_matrix)
ps = np.bincount(s) / float(len(s))


In [ ]:
s

array([28,  5, 13, ..., 15, 20,  2])

In [ ]:
# vectorizer = TfidfVectorizer(sublinear_tf=False,smooth_idf=True, max_df=0.9,ngram_range=[1,5], stop_words='english', use_idf=True)

In [ ]:
# vectorizer = TfidfVectorizer(sublinear_tf=False,smooth_idf=True, max_df=0.9,ngram_range=[1,5], use_idf=False)

In [ ]:
vectorizer = CountVectorizer(min_df=.01, max_df=.8, ngram_range=[1,3], max_features=300)

In [ ]:
X_train

<9298x226 sparse matrix of type '<class 'numpy.int64'>'
	with 70967 stored elements in Compressed Sparse Row format>

In [ ]:
X_train = vectorizer.fit_transform(X_train)
X_val = vectorizer.fit_transform(X_val)

In [ ]:
X_train

<9298x226 sparse matrix of type '<class 'numpy.int64'>'
	with 70967 stored elements in Compressed Sparse Row format>

In [ ]:
X_val

<2325x224 sparse matrix of type '<class 'numpy.int64'>'
	with 17568 stored elements in Compressed Sparse Row format>

In [ ]:
#count_vect_df = pd.DataFrame(X_train.todense(), columns=vectorizer.get_feature_names())

In [ ]:
pd.concat([X_train, count_vect_df], axis=1)

NameError: ignored

In [ ]:
from cleanlab.latent_estimation import estimate_cv_predicted_probabilities
from cleanlab.pruning import get_noise_indices
# Find the indices of label errors in 2 lines of code.

probabilities = estimate_cv_predicted_probabilities(
    X_train, 
    s, 
    clf=RandomForestClassifier(),
)


ValueError: ignored

In [ ]:
label_error_indices = get_noise_indices(
    s = s, 
    psx = probabilities, 
)

In [ ]:
baseline_cl_both = get_noise_indices(
            s, probabilities, prune_method='both')

In [ ]:
X_train2 = vectorizer.inverse_transform(X_train)
X_val2 = vectorizer.inverse_transform(X_val)

In [ ]:
X_train

In [ ]:
baseline_cl_both

In [ ]:
Wad_dis = class_le.inverse_transform(s)
Wad_dis2 = class_le.inverse_transform(y_val)
omg_pls = class_le.inverse_transform(y_train)

In [ ]:
# from __future__ import print_function, absolute_import, division, unicode_literals, with_statement
# from numpy.random import multivariate_normal
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score
# import numpy as np


# import cleanlab
# from cleanlab.noise_generation import generate_noise_matrix_from_trace, generate_noisy_labels
# from cleanlab.util import print_noise_matrix
# from cleanlab.latent_estimation import estimate_confident_joint_and_cv_pred_proba, estimate_latent
# from cleanlab.pruning import get_noise_indices
# from cleanlab.classification import LearningWithNoisyLabels

In [ ]:
# confident_joint, psx = estimate_confident_joint_and_cv_pred_proba(X_train, s, seed=42)
# est_py, est_noise_matrix, est_inverse_noise_matrix = estimate_latent(confident_joint, s)
# idx_errors = get_noise_indices(s, psx)

In [ ]:
df = pd.read_csv(project_path + 'public_data.csv')

In [ ]:
X = df['message']
y = df['label']

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
yy = {'Noise':baseline_cl_both,'label_thingy':s,'inversed':Wad_dis,'xtraincompare':X_train2,'realxtrain':X_train,'ytrain':omg_pls}
see_df = pd.DataFrame(yy)

In [ ]:
tt = {'xval':X_val,'yval':y_val,'truelab':Wad_dis2}
see_df2 = pd.DataFrame(tt)

In [ ]:
see_df

In [ ]:
see_df2

In [ ]:
see_df.to_csv('ehhh.csv', index=False)

In [ ]:
see_df2.to_csv('Yval.csv', index=False)

In [ ]:
from cleanlab.latent_estimation import (
  estimate_latent, estimate_confident_joint_and_cv_pred_proba
)

# Compute the confident joint and psx (n x m predicted probabilities matrix),
# for n examples, m classes.
confident_joint, psx = estimate_confident_joint_and_cv_pred_proba(
    X=X_train, 
    s=s,
    clf=RandomForestClassifier(), # default, you can use any classifier
)

# Estimate the latent statistics (distributions)
#  - Latent Prior: est_py is the array p(y)
#  - Noisy Channel / Noise Transition Matrix: est_nm is the matrix P(s|y) 
#  - Inverse Noise Matrix: est_inv is the matrix P(y|s)
est_py, est_nm, est_inv = estimate_latent(
    confident_joint, s=s)

/usr/local/lib/python3.7/dist-packages/cleanlab/latent_algebra.py:253: RuntimeWarning: invalid value encountered in true_divide
  py = inverse_noise_matrix.diagonal() / noise_matrix.diagonal() * ps


In [ ]:
est_inv[0]

array([0.78070175, 0.02702703, 0.0026738 , 0.        , 0.        ,
       0.        , 0.        , 0.01204819, 0.        , 0.00393701,
       0.00414938, 0.00591716, 0.        , 0.        , 0.        ,
       0.00515464, 0.        , 0.        , 0.02083333, 0.        ,
       0.        , 0.        , 0.        , 0.01492537, 0.03846154,
       0.        , 0.00469484, 0.        , 0.00273224, 0.00471698,
       0.00440529, 0.        , 0.03703704, 0.00497512, 0.00308642,
       0.        , 0.        ])

In [ ]:
from cleanlab.latent_estimation import (
    estimate_py_noise_matrices_and_cv_pred_proba
)

est_py, est_nm, est_inv, confident_joint, psx = (
    estimate_py_noise_matrices_and_cv_pred_proba(
        X=X_train,
        s=s,
    )
)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [ ]:
len(est_inv)

37

In [ ]:
X_val

<2325x224 sparse matrix of type '<class 'numpy.int64'>'
	with 17568 stored elements in Compressed Sparse Row format>

In [ ]:
from cleanlab.classification import LearningWithNoisyLabels
from sklearn.linear_model import LogisticRegression as LogReg
rp = LearningWithNoisyLabels(clf=LogReg()) # Pass in any classifier.
rp.fit(X_train, y_train)
# Estimate the predictions as if you had trained without label errors.
pred = rp.predict(X_val)

ValueError: ignored

In [ ]:
from __future__ import (print_function, absolute_import, division,
                        unicode_literals, with_statement)
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import ParameterGrid
import numpy as np
from cleanlab.classification import LearningWithNoisyLabels
from cleanlab.noise_generation import generate_noisy_labels
from cleanlab.util import value_counts
from cleanlab.latent_algebra import compute_inv_noise_matrix

In [ ]:
X = df['message']
y = df['label']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# # Seed for reproducibility
# seed = 2
# clf = LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=1000)
# rp = LearningWithNoisyLabels(clf=clf, seed=seed)
# np.random.seed(seed=seed)

# # Get iris dataset
# iris = datasets.load_iris()
# X = iris.data  # we only take the first two features.
# y = iris.target
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

try:
    get_ipython().run_line_magic('matplotlib', 'inline')
    from matplotlib import pyplot as plt

    _ = plt.figure(figsize=(12, 8))
    color_list = plt.cm.tab10(np.linspace(0, 1, 6))
    _ = plt.scatter(X_train[:, 1], X_train[:, 3],
                    color=[color_list[z] for z in y_train], s=50)
    ax = plt.gca()
    #     plt.axis('off')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    _ = ax.get_xaxis().set_ticks([])
    _ = ax.get_yaxis().set_ticks([])
    _ = plt.title("Iris dataset (feature 3 vs feature 1)", fontsize=30)
except Exception as e:
    print(e)
    print("Plotting is only supported in an iPython interface.")

'key of type tuple not found and not a MultiIndex'
Plotting is only supported in an iPython interface.


<Figure size 864x576 with 0 Axes>

In [ ]:
y_train

array([2, 0, 1, 2, 1, 0, 2, 1, 1, 2, 1, 1, 2, 1, 0, 2, 0, 1, 0, 0, 0, 2,
       2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 1, 1, 2, 2, 1, 0, 1, 0, 2, 1, 1, 0,
       1, 1, 1, 2, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 2, 2, 0, 0, 2, 2, 1, 2,
       1, 1, 2, 0, 2, 2, 2, 0, 2, 0, 0, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2,
       1, 2, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 2, 0, 1,
       0, 2, 1, 0, 2, 1, 0, 0, 1, 0])

In [ ]:
# Generate lots of noise.
noise_matrix = np.array([
    [0.5, 0.0, 0.0],
    [0.5, 1.0, 0.5],
    [0.0, 0.0, 0.5],
])

py = value_counts(y_train)
# Create noisy labels
s = generate_noisy_labels(y_train, noise_matrix)

try:
    get_ipython().run_line_magic('matplotlib', 'inline')
    from matplotlib import pyplot as plt

    _ = plt.figure(figsize=(15, 8))
    color_list = plt.cm.tab10(np.linspace(0, 1, 6))
    for k in range(len(np.unique(y_train))):
        X_k = X_train[y_train == k]  # data for class k
        _ = plt.scatter(
            X_k[:, 1],
            X_k[:, 3],
            color=[color_list[noisy_label] for noisy_label in s[y_train == k]],
            s=200,
            marker=r"${a}$".format(a=str(k)),
            linewidth=1,
        )
    _ = plt.scatter(
        x=X_train[s != y_train][:, 1],
        y=X_train[s != y_train][:, 3],
        color=[color_list[z] for z in s],
        s=400,
        facecolors='none',
        edgecolors='black',
        linewidth=2,
        alpha=0.5,
    )
    ax = plt.gca()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    _ = ax.get_xaxis().set_ticks([])
    _ = ax.get_yaxis().set_ticks([])
    _ = plt.title("Iris dataset (features 3 and 1). Label errors circled.",
                  fontsize=30)
except Exception as e:
    print(e)
    print("Plotting is only supported in an iPython interface.")

ValueError: ignored

In [ ]:
print('WITHOUT confident learning,', end=" ")
clf = LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=1000)
_ = clf.fit(X_train, s)
pred = clf.predict(X_test)
print("Iris dataset test accuracy:", round(accuracy_score(pred, y_test), 2))

print("\nNow we show improvement using cleanlab to characterize the noise")
print("and learn on the data that is (with high confidence) labeled correctly.")
print()
print('WITH confident learning (noise matrix given),', end=" ")
_ = rp.fit(X_train, s, noise_matrix=noise_matrix)
pred = rp.predict(X_test)
print("Iris dataset test accuracy:", round(accuracy_score(pred, y_test), 2))

print('WITH confident learning (noise / inverse noise matrix given),', end=" ")
inv = compute_inv_noise_matrix(py, noise_matrix)
_ = rp.fit(X_train, s, noise_matrix=noise_matrix, inverse_noise_matrix=inv)
pred = rp.predict(X_test)
print("Iris dataset test accuracy:", round(accuracy_score(pred, y_test), 2))

print('WITH confident learning noise not given,', end=" ")
clf = LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=1000)
rp = LearningWithNoisyLabels(clf=clf, seed=seed)
_ = rp.fit(X_train, s)
pred = rp.predict(X_test)
print("Iris dataset test accuracy:", round(accuracy_score(pred, y_test), 2))

WITHOUT confident learning, Iris dataset test accuracy: 0.6

Now we show improvement using cleanlab to characterize the noise
and learn on the data that is (with high confidence) labeled correctly.

WITH confident learning (noise matrix given), Iris dataset test accuracy: 0.83
WITH confident learning (noise / inverse noise matrix given), Iris dataset test accuracy: 0.83
WITH confident learning noise not given, Iris dataset test accuracy: 0.77


In [ ]:
param_grid = {
    "prune_method": ["prune_by_noise_rate", "prune_by_class", "both"],
    "converge_latent_estimates": [True, False],
}

# Fit LearningWithNoisyLabels across all parameter settings.
params = ParameterGrid(param_grid)
scores = []
for param in params:
    clf = LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=1000)
    rp = LearningWithNoisyLabels(clf=clf, n_jobs=1, **param)
    _ = rp.fit(X_train, s)  # s is the noisy y_train labels
    scores.append(accuracy_score(rp.predict(X_test), y_test))

# Print results sorted from best to least
for i in np.argsort(scores)[::-1]:
    print("Param settings:", params[i])
    print(
        "Iris dataset test accuracy (using confident learning):\t",
        round(scores[i], 2),
        "\n",
    )

Param settings: {'prune_method': 'prune_by_class', 'converge_latent_estimates': False}
Iris dataset test accuracy (using confident learning):	 0.83 

Param settings: {'prune_method': 'prune_by_class', 'converge_latent_estimates': True}
Iris dataset test accuracy (using confident learning):	 0.83 

Param settings: {'prune_method': 'both', 'converge_latent_estimates': False}
Iris dataset test accuracy (using confident learning):	 0.8 

Param settings: {'prune_method': 'both', 'converge_latent_estimates': True}
Iris dataset test accuracy (using confident learning):	 0.8 

Param settings: {'prune_method': 'prune_by_noise_rate', 'converge_latent_estimates': False}
Iris dataset test accuracy (using confident learning):	 0.77 

Param settings: {'prune_method': 'prune_by_noise_rate', 'converge_latent_estimates': True}
Iris dataset test accuracy (using confident learning):	 0.77 



In [ ]:
param_grid = {
    "prune_method": ["prune_by_noise_rate", "prune_by_class", "both"],
    "converge_latent_estimates": [True, False],
}

# Fit LearningWithNoisyLabels across all parameter settings.
params = ParameterGrid(param_grid)
scores = []
for param in params:
    clf = LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=1000)
    rp = LearningWithNoisyLabels(clf=clf, n_jobs=1, **param)
    _ = rp.fit(X_train, s)  # s is the noisy y_train labels
    scores.append(accuracy_score(rp.predict(X_test), y_test))

# Print results sorted from best to least
for i in np.argsort(scores)[::-1]:
    print("Param settings:", params[i])
    print(
        "Iris dataset test accuracy (using confident learning):\t",
        round(scores[i], 2),
        "\n",
    )

Param settings: {'prune_method': 'prune_by_noise_rate', 'converge_latent_estimates': True}
Iris dataset test accuracy (using confident learning):	 0.87 

Param settings: {'prune_method': 'both', 'converge_latent_estimates': False}
Iris dataset test accuracy (using confident learning):	 0.83 

Param settings: {'prune_method': 'prune_by_class', 'converge_latent_estimates': False}
Iris dataset test accuracy (using confident learning):	 0.83 

Param settings: {'prune_method': 'prune_by_noise_rate', 'converge_latent_estimates': False}
Iris dataset test accuracy (using confident learning):	 0.77 

Param settings: {'prune_method': 'both', 'converge_latent_estimates': True}
Iris dataset test accuracy (using confident learning):	 0.77 

Param settings: {'prune_method': 'prune_by_class', 'converge_latent_estimates': True}
Iris dataset test accuracy (using confident learning):	 0.77 

