In [1]:
pip install tqdm

In [2]:
pip install transformers

     |████████████████████████████████| 4.0 MB 5.2 MB/s 
     |████████████████████████████████| 596 kB 43.5 MB/s 
     |████████████████████████████████| 77 kB 3.9 MB/s 
     |████████████████████████████████| 6.6 MB 36.2 MB/s 
     |████████████████████████████████| 895 kB 36.7 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
# pip install simpletransformers

     |████████████████████████████████| 249 kB 3.9 MB/s 
     |████████████████████████████████| 6.6 MB 55.6 MB/s 
     |████████████████████████████████| 1.2 MB 88.3 MB/s 
     |████████████████████████████████| 10.1 MB 70.1 MB/s 
     |████████████████████████████████| 43 kB 2.6 MB/s 
     |████████████████████████████████| 4.0 MB 49.7 MB/s 
     |████████████████████████████████| 1.8 MB 50.0 MB/s 
     |████████████████████████████████| 325 kB 63.8 MB/s 
     |████████████████████████████████| 596 kB 11.7 MB/s 
     |████████████████████████████████| 895 kB 60.9 MB/s 
     |████████████████████████████████| 77 kB 6.1 MB/s 
     |████████████████████████████████| 181 kB 63.5 MB/s 
     |████████████████████████████████| 144 kB 57.0 MB/s 
     |████████████████████████████████| 63 kB 2.0 MB/s 
     |████████████████████████████████| 1.1 MB 54.1 MB/s 
     |████████████████████████████████| 136 kB 62.3 MB/s 
     |████████████████████████████████| 212 kB 71.0 MB/s 
     |██████████████

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
import xgboost as XGBClassifier
from sklearn.ensemble import RandomForestClassifier
#import simpletransformers
from sklearn.model_selection import GridSearchCV
import re
import nltk
from nltk.corpus import stopwords
#from simpletransformers.classification import ClassificationModel
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
import pandas as pd
import sklearn
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics.cluster import adjusted_mutual_info_score



In [4]:
#mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
project_path = '/content/drive/MyDrive/NLP/'
 

In [6]:
df = pd.read_csv(project_path + 'public_data.csv')
df_test = pd.read_csv(project_path + 'input_data.csv') 
########## For people running locally#####
#emails_df2 = pd.read_csv('enron_classification_df.csv') 

In [ ]:
#####################Base Code#####################

In [ ]:


# #df = pd.read_csv("public_data.csv")
# print(df.info())
# print(df.head())


# X = df['message']
# y = df['label']

# X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# print(X_train.shape)
# print(y_train.shape)
# print(X_val.shape)
# print(y_val.shape)


# vectorizer = CountVectorizer(min_df=.01, max_df=.8, ngram_range=[1,1], max_features=300, stop_words='english')

# pipe = Pipeline([('vec', vectorizer),  ('clf', DecisionTreeClassifier(random_state=223))])

# pipe.fit(X_train, y_train)


# from sklearn.metrics import confusion_matrix, classification_report

# pred_val = pipe.predict(X_val)
# print(confusion_matrix(y_val, pred_val))
# print(classification_report(y_val, pred_val))


# from sklearn.metrics.cluster import adjusted_rand_score, adjusted_mutual_info_score

# ari = adjusted_rand_score(y_val, pred_val)
# ami = adjusted_mutual_info_score(y_val, pred_val, average_method='arithmetic')

# print("ARI: {}".format(ari))
# print("AMI: {}".format(ami))


# ## Kaggle Predictions


# #df_test = pd.read_csv('input_data.csv')
# df_test.info()
# df_test.head()

# pred_test = pipe.predict(df_test['message'])

# my_submission = pd.DataFrame({'Id': df_test['id'], 'label': pred_test})
# print(my_submission.head())

# # NOTE: after saving the CSV file, be sure to zip the file before submitting to the competition website!
# my_submission.to_csv('answers.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11623 entries, 0 to 11622
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   message  11623 non-null  object
 1   label    11623 non-null  object
dtypes: object(2)
memory usage: 181.7+ KB
None
                                             message                label
0  my credit card was missed so please close the ...       reportlostcard
1                             i need a boarding pass      getboardingpass
2                need a proof of insurance of my car  getproofofinsurance
3                           i want to change address        updateaddress
4              hi i want to check my seat assignemnt          getseatinfo
(9298,)
(9298,)
(2325,)
(2325,)
[[ 49   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0 170 ...   0   0   0]
 ...
 [  0   0   0 ...  74   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   9]]
                       precis

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [7]:
from sklearn.preprocessing import LabelEncoder
def label_encoder(data):
    class_le = LabelEncoder()    
    h = class_le.fit_transform(df['label'].astype(str))
    return h

In [8]:
class_le = LabelEncoder() 

In [9]:
df

id                                            message  \
0          1    hi i want change my address from my credit card   
1          2                                   classic caesar 2   
2          3  i like to order 3 meat eater and 1 art lover p...   
3          4                   i need reimbursement my expenses   
4          5              i need a copy of insurance for my car   
...      ...                                                ...   
21639  21640         i would like to have 3 medium green stripe   
21640  21641  boarding pass to be sent to your email address...   
21641  21642                           i want musical equipment   
21642  21643                                 i need window seat   
21643  21644              please money transfer from my account   

                      label  
0             updateaddress  
1          ordersaladintent  
2          orderpizzaintent  
3             expensereport  
4       getproofofinsurance  
...                     ...  
21639      orderpizzaintent  
21640       getboardingpass  
21641            startorder  
21642  changeseatassignment  
21643         transfermoney  

[21644 rows x 3 columns]

In [10]:
pip install datasets

     |████████████████████████████████| 325 kB 5.2 MB/s 
     |████████████████████████████████| 1.1 MB 52.7 MB/s 
     |████████████████████████████████| 212 kB 65.9 MB/s 
     |████████████████████████████████| 136 kB 39.9 MB/s 
     |████████████████████████████████| 127 kB 52.1 MB/s 
     |████████████████████████████████| 94 kB 3.3 MB/s 
     |████████████████████████████████| 144 kB 61.1 MB/s 
     |████████████████████████████████| 271 kB 64.4 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.


In [11]:
# Read data
data = pd.read_csv(project_path + 'input_data.csv')

In [12]:
from sklearn.utils import shuffle
data = shuffle(data)

In [13]:
data['label']= class_le.fit_transform(data['label'].astype(str))


In [14]:
data['message'] = data['message'].str.lower()

In [15]:
data

id                                            message  label
19579  19580                                i want update skype     29
5147    5148                                my phone is damaged     26
6553    6554                           yes like to have a pizza     21
11778  11779                                    yes 1 smore pie     19
6104    6105  hello i am here to get a proof of insurance fo...     13
...      ...                                                ...    ...
1304    1305             i need one serious help about my skype     27
13463  13464                      travel that i need reimbursed      9
15601  15602                       i had some issue in my skype     27
9877    9878  i want do transfer money from my account to my...     33
9399    9400  outlook app not opened and message not send pr...     27

[21644 rows x 3 columns]

In [16]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
import torch
from transformers import TrainingArguments, Trainer
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import EarlyStoppingCallback


# Read data
#data = pd.read_csv(project_path + 'public_data.csv')

# Define pretrained tokenizer and model
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name, num_labels=37)

# ----- 1. Preprocess data -----#
# Preprocess data
X = list(data["message"])
y = list(data["label"])
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
X_train_tokenized = tokenizer(X_train, padding=True, truncation=True, max_length=512)
X_val_tokenized = tokenizer(X_val, padding=True, truncation=True, max_length=512)

# Create torch dataset
class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        if self.labels:
            item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.encodings["input_ids"])

train_dataset = Dataset(X_train_tokenized, y_train)
val_dataset = Dataset(X_val_tokenized, y_val)



Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/420M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [17]:
# ----- 2. Fine-tune pretrained model -----#
# Define Trainer parameters
from sklearn.metrics.cluster import adjusted_rand_score, adjusted_mutual_info_score
def compute_metrics(p):
    pred, labels = p
    pred = np.argmax(pred, axis=1)

    accuracy = accuracy_score(y_true=labels, y_pred=pred)
    ari = adjusted_rand_score(labels, pred)
    ami = adjusted_mutual_info_score(labels, pred, average_method='arithmetic')
    #recall = recall_score(y_true=labels, y_pred=pred,average='macro')
    #precision = precision_score(y_true=labels, y_pred=pred,average='macro')
    f1 = f1_score(y_true=labels, y_pred=pred,average='macro')

    #return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}
    return {"accuracy": accuracy, "ARI": ari, "AMI": ami, "f1": f1}

# Define Trainer
args = TrainingArguments(
    output_dir="output",
    evaluation_strategy="steps",
    eval_steps=500,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=10,
    seed=0,
    load_best_model_at_end=True,
)
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=7)],
)

# Train pre-trained model
trainer.train()



/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
***** Running training *****
  Num examples = 17315
  Num Epochs = 10
  Instantaneous batch size per device = 8
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 1
  Total optimization steps = 21650


***** Running Evaluation *****
  Num examples = 4329
  Batch size = 8
Saving model checkpoint to output/checkpoint-500
Configuration saved in output/checkpoint-500/config.json
Model weights saved in output/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 4329
  Batch size = 8
Saving model checkpoint to output/checkpoint-1000
Configuration saved in output/checkpoint-1000/config.json
Model weights saved in output/checkpoint-1000/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 4329
  Batch size = 8
Saving model checkpoint to output/checkpoint-1500
Configuration saved in output/checkpoint-1500/config.json
Model weights saved in output/checkpoint-1500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 4329
  Batch size = 8
Saving model checkpoint to output/checkpoint-2000
Configuration saved in output/checkpoint-2000/config.json
Model weights saved in output/checkpoint-2000/pytorch_model.bin
***** Running Evaluation *****
  Nu

TrainOutput(global_step=11500, training_loss=0.06695325268869814, metrics={'train_runtime': 1385.6653, 'train_samples_per_second': 124.958, 'train_steps_per_second': 15.624, 'total_flos': 2694947094245250.0, 'train_loss': 0.06695325268869814, 'epoch': 5.31})

In [18]:
# ----- 3. Predict -----#
# Load test data
test_data = pd.read_csv(project_path + 'input_data.csv')
X_test = list(test_data["message"])
X_test_tokenized = tokenizer(X_test, padding=True, truncation=True, max_length=512)

# Create torch dataset
test_dataset = Dataset(X_test_tokenized)

# Load trained model
model_path = "output/checkpoint-8000"
model = BertForSequenceClassification.from_pretrained(model_path, num_labels=37)

# Define test trainer
test_trainer = Trainer(model)

# Make prediction
raw_pred, _, _ = test_trainer.predict(test_dataset)

# Preprocess raw predictions
y_pred = np.argmax(raw_pred, axis=1)

loading configuration file output/checkpoint-8000/config.json
Model config BertConfig {
  "_name_or_path": "bert-base-uncased",
  "architectures": [
    "BertForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4",
    "5": "LABEL_5",
    "6": "LABEL_6",
    "7": "LABEL_7",
    "8": "LABEL_8",
    "9": "LABEL_9",
    "10": "LABEL_10",
    "11": "LABEL_11",
    "12": "LABEL_12",
    "13": "LABEL_13",
    "14": "LABEL_14",
    "15": "LABEL_15",
    "16": "LABEL_16",
    "17": "LABEL_17",
    "18": "LABEL_18",
    "19": "LABEL_19",
    "20": "LABEL_20",
    "21": "LABEL_21",
    "22": "LABEL_22",
    "23": "LABEL_23",
    "24": "LABEL_24",
    "25": "LABEL_25",
    "26": "LABEL_26",
    "27": "LABEL_27",
    "28": "LABEL_2

In [19]:
y_pred

array([27, 21, 25, ..., 17, 13, 22])

In [20]:
predictions = class_le.inverse_transform(y_pred)

In [21]:
my_submission = pd.DataFrame({'id': test_data.id, 'predicted': predictions})

In [22]:
my_submission

id             predicted
0     12123  reportbrokensoftware
1       244      orderpizzaintent
2      8221           replacecard
3     12856    startserviceintent
4     12108         expensereport
...     ...                   ...
2901   7124      checkclaimstatus
2902  13534  getinformationintent
2903   1678     orderburgerintent
2904   6154   getproofofinsurance
2905    615      ordersaladintent

[2906 rows x 2 columns]

In [23]:
# NOTE: after saving the CSV file, be sure to zip the file before submitting to the competition website!
my_submission.to_csv('BertUncasedFinal.csv', index=False)

In [25]:
from google.colab import files
files.download("BertUncasedFinal.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>