In [1]:
pip install tqdm

In [2]:
pip install simpletransformers

     |████████████████████████████████| 249 kB 5.1 MB/s 
     |████████████████████████████████| 325 kB 81.7 MB/s 
     |████████████████████████████████| 6.6 MB 58.0 MB/s 
     |████████████████████████████████| 1.2 MB 47.8 MB/s 
     |████████████████████████████████| 4.0 MB 52.9 MB/s 
     |████████████████████████████████| 43 kB 1.8 MB/s 
     |████████████████████████████████| 1.8 MB 55.1 MB/s 
     |████████████████████████████████| 10.1 MB 42.1 MB/s 
     |████████████████████████████████| 596 kB 68.3 MB/s 
     |████████████████████████████████| 895 kB 69.7 MB/s 
     |████████████████████████████████| 77 kB 5.1 MB/s 
     |████████████████████████████████| 144 kB 57.1 MB/s 
     |████████████████████████████████| 181 kB 48.1 MB/s 
     |████████████████████████████████| 63 kB 2.0 MB/s 
     |████████████████████████████████| 212 kB 73.1 MB/s 
     |████████████████████████████████| 136 kB 49.7 MB/s 
     |████████████████████████████████| 1.1 MB 62.3 MB/s 
     |██████████████

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
import xgboost as XGBClassifier
from sklearn.ensemble import RandomForestClassifier
import simpletransformers
from sklearn.model_selection import GridSearchCV
import re
import nltk
from nltk.corpus import stopwords
from simpletransformers.classification import ClassificationModel
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
import pandas as pd
import sklearn
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics.cluster import adjusted_mutual_info_score



In [2]:
#mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
project_path = '/content/drive/MyDrive/NLP/'
 

In [4]:
df = pd.read_csv(project_path + 'public_data.csv')
df_test = pd.read_csv(project_path + 'input_data.csv') 
########## For people running locally#####
#emails_df2 = pd.read_csv('enron_classification_df.csv') 

In [5]:
df.tail()

id                                            message  \
21639  21640         i would like to have 3 medium green stripe   
21640  21641  boarding pass to be sent to your email address...   
21641  21642                           i want musical equipment   
21642  21643                                 i need window seat   
21643  21644              please money transfer from my account   

                      label  
21639      orderpizzaintent  
21640       getboardingpass  
21641            startorder  
21642  changeseatassignment  
21643         transfermoney

In [6]:
from sklearn.utils import shuffle
df = shuffle(df)

In [ ]:
#####################Base Code#####################

In [ ]:


# #df = pd.read_csv("public_data.csv")
# print(df.info())
# print(df.head())


# X = df['message']
# y = df['label']

# X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# print(X_train.shape)
# print(y_train.shape)
# print(X_val.shape)
# print(y_val.shape)


# vectorizer = CountVectorizer(min_df=.01, max_df=.8, ngram_range=[1,1], max_features=300, stop_words='english')

# pipe = Pipeline([('vec', vectorizer),  ('clf', DecisionTreeClassifier(random_state=223))])

# pipe.fit(X_train, y_train)


# from sklearn.metrics import confusion_matrix, classification_report

# pred_val = pipe.predict(X_val)
# print(confusion_matrix(y_val, pred_val))
# print(classification_report(y_val, pred_val))


# from sklearn.metrics.cluster import adjusted_rand_score, adjusted_mutual_info_score

# ari = adjusted_rand_score(y_val, pred_val)
# ami = adjusted_mutual_info_score(y_val, pred_val, average_method='arithmetic')

# print("ARI: {}".format(ari))
# print("AMI: {}".format(ami))


# ## Kaggle Predictions


# #df_test = pd.read_csv('input_data.csv')
# df_test.info()
# df_test.head()

# pred_test = pipe.predict(df_test['message'])

# my_submission = pd.DataFrame({'Id': df_test['id'], 'label': pred_test})
# print(my_submission.head())

# # NOTE: after saving the CSV file, be sure to zip the file before submitting to the competition website!
# my_submission.to_csv('answers.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11623 entries, 0 to 11622
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   message  11623 non-null  object
 1   label    11623 non-null  object
dtypes: object(2)
memory usage: 181.7+ KB
None
                                             message                label
0  my credit card was missed so please close the ...       reportlostcard
1                             i need a boarding pass      getboardingpass
2                need a proof of insurance of my car  getproofofinsurance
3                           i want to change address        updateaddress
4              hi i want to check my seat assignemnt          getseatinfo
(9298,)
(9298,)
(2325,)
(2325,)
[[ 49   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0 170 ...   0   0   0]
 ...
 [  0   0   0 ...  74   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   9]]
                       precis

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [ ]:
# import nltk
# nltk.download('stopwords')
# import nltk
# nltk.download('wordnet')

In [ ]:
# # importing the library needed in this section
# from nltk.stem import WordNetLemmatizer


# # instantiating the lemmaztizer object
# lemmatizer = WordNetLemmatizer()

# # lemmatizing each word through a list comprehension
# X = [lemmatizer.lemmatize(token) for token in df['message']]

In [ ]:
# from nltk.corpus import stopwords
# nltk.download('stopwords')
# stop_words = stopwords.words('english')
# df['message'] = df['message'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [7]:
from sklearn.preprocessing import LabelEncoder
def label_encoder(data):
    class_le = LabelEncoder()    
    h = class_le.fit_transform(df['label'].astype(str))
    return h

In [8]:
class_le = LabelEncoder() 

In [9]:
y2 = class_le.fit_transform(df['label'].astype(str))


In [10]:
d = {'message':df['message'].str.lower(),'label':y2}
df_mock = pd.DataFrame(d)

In [11]:
df_mock.tail()

message  label
16243  i like to order 2 meat eater and and 1 bbq piz...     21
3735                     hi i wants to purchase internet     31
15732                      can i change to an aisle seat      2
16262            seat assignment and decide to change it      2
8137                  i want to check my seat assignment      2

In [ ]:
# prepare cross validation
n=5
kf = KFold(n_splits=n, random_state=42, shuffle=True)

results = []

for train_index, val_index in kf.split(df_mock):
  # splitting Dataframe (dataset not included)
    train_df = df_mock.iloc[train_index]
    val_df = df_mock.iloc[val_index]



In [ ]:
# Using 'bert-large-uncased' here. For a list of other models, please refer to 
# https://github.com/ThilinaRajapakse/simpletransformers/#current-pretrained-models 
roberta_uncased = ClassificationModel('roberta', 'roberta-base') 

# Print out all the default arguments for reference
roberta_uncased.args

Downloading:   0%|          | 0.00/481 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/478M [00:00<?, ?B/s]

Some weights of the model checkpoint at roberta-base were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'lm_head.decoder.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.dense.weight', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.out_proj.weight', 'classi

Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

ClassificationArgs(adafactor_beta1=None, adafactor_clip_threshold=1.0, adafactor_decay_rate=-0.8, adafactor_eps=(1e-30, 0.001), adafactor_relative_step=True, adafactor_scale_parameter=True, adafactor_warmup_init=True, adam_epsilon=1e-08, best_model_dir='outputs/best_model', cache_dir='cache_dir/', config={}, cosine_schedule_num_cycles=0.5, custom_layer_parameters=[], custom_parameter_groups=[], dataloader_num_workers=0, do_lower_case=False, dynamic_quantize=False, early_stopping_consider_epochs=False, early_stopping_delta=0, early_stopping_metric='eval_loss', early_stopping_metric_minimize=True, early_stopping_patience=3, encoding=None, eval_batch_size=8, evaluate_during_training=False, evaluate_during_training_silent=True, evaluate_during_training_steps=2000, evaluate_during_training_verbose=False, evaluate_each_epoch=True, fp16=True, gradient_accumulation_steps=1, learning_rate=4e-05, local_rank=-1, logging_steps=50, loss_type=None, loss_args={}, manual_seed=None, max_grad_norm=1.0, 

In [ ]:
# This is where we can tweak based on the default arguments above
custom_args = {'fp16': False, # not using mixed precision 
               'train_batch_size': 4, # default is 8
               'gradient_accumulation_steps': 2,
               'do_lower_case': True,
               'learning_rate': 1e-05, # using lower learning rate
               'overwrite_output_dir': True, # important for CV
               'num_train_epochs': 2} # default is 1

In [ ]:
# prepare cross validation
n=5
kf = KFold(n_splits=n, random_state=42, shuffle=True)
results = []

for train_index, val_index in kf.split(df_mock):
    # splitting Dataframe (dataset not included)
    train_df = df_mock.iloc[train_index]
    val_df = df_mock.iloc[val_index]
    
    model = ClassificationModel('roberta', 'roberta-base', num_labels=37,use_cuda=True, args={'learning_rate':1e-5, 'num_train_epochs': 1, 'reprocess_input_data': True, 'overwrite_output_dir': True}) 
    model.train_model(train_df)
    result, model_outputs, wrong_predictions = model.eval_model(val_df, acc=sklearn.metrics.accuracy_score)
    print(result['acc'])
    results.append(result['acc'])

In [30]:
from sklearn.metrics.cluster import adjusted_mutual_info_score
# validate the model 
result, model_outputs, wrong_predictions = model.eval_model(val_df, acc=sklearn.metrics.adjusted_rand_score)
print(result['acc'])
# append model score
results.append(result['acc'])

In [ ]:
from sklearn.metrics.cluster import adjusted_mutual_info_score
# validate the model 
result, model_outputs, wrong_predictions = model.eval_model(val_df, acc=sklearn.metrics.adjusted_mutual_info_score)
print(result['acc'])
# append model score
results.append(result['acc'])

In [12]:
#Train on full DF
model = ClassificationModel('roberta', 'roberta-base', num_labels=37,use_cuda=True, args={'learning_rate':1e-6, 'num_train_epochs': 11, 'reprocess_input_data': True, 'overwrite_output_dir': True}) 
model.train_model(df_mock)


Downloading:   0%|          | 0.00/481 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/478M [00:00<?, ?B/s]

Some weights of the model checkpoint at roberta-base were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'roberta.pooler.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.decoder.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.

Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

/usr/local/lib/python3.7/dist-packages/simpletransformers/classification/classification_model.py:586: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."


  0%|          | 0/21644 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,


Epoch:   0%|          | 0/11 [00:00<?, ?it/s]

Running Epoch 0 of 11:   0%|          | 0/2706 [00:00<?, ?it/s]

Running Epoch 1 of 11:   0%|          | 0/2706 [00:00<?, ?it/s]

Running Epoch 2 of 11:   0%|          | 0/2706 [00:00<?, ?it/s]

Running Epoch 3 of 11:   0%|          | 0/2706 [00:00<?, ?it/s]

Running Epoch 4 of 11:   0%|          | 0/2706 [00:00<?, ?it/s]

Running Epoch 5 of 11:   0%|          | 0/2706 [00:00<?, ?it/s]

Running Epoch 6 of 11:   0%|          | 0/2706 [00:00<?, ?it/s]

Running Epoch 7 of 11:   0%|          | 0/2706 [00:00<?, ?it/s]

Running Epoch 8 of 11:   0%|          | 0/2706 [00:00<?, ?it/s]

Running Epoch 9 of 11:   0%|          | 0/2706 [00:00<?, ?it/s]

Running Epoch 10 of 11:   0%|          | 0/2706 [00:00<?, ?it/s]

(29766, 0.3677823189627233)

In [13]:
# # Test Model 2
# model = ClassificationModel('roberta', 'roberta-large', num_labels=37,use_cuda=True, args={'learning_rate':1e-5, 'num_train_epochs': 10, 'reprocess_input_data': True, 'overwrite_output_dir': True}) 
# model.train_model(df_mock)


In [14]:
# # Test Model 3
# model = ClassificationModel('bert', 'bert-base-uncased', num_labels=37,use_cuda=True, args={'learning_rate':1e-5, 'num_train_epochs': 10, 'reprocess_input_data': True, 'overwrite_output_dir': True})
# model.train_model(df_mock)

In [27]:
test_clean = df_test

In [28]:
test_clean

id                                            message
0     12123                            i have problem in excel
1       244  i need \t pesto drizzle over grilled chicken c...
2      8221  need to help order a new card as the old one e...
3     12856                               i need internet plan
4     12108                               my are report travel
...     ...                                                ...
2901   7124                     i wants to know about my claim
2902  13534       is there any changes in future for this plan
2903   1678  i need a cheese burger without pickles and a b...
2904   6154                   i want a proof of insurance copy
2905    615          yes i like to 1 arugula fresh fruit salad

[2906 rows x 2 columns]

In [17]:
# # importing the library needed in this section
# from nltk.stem import WordNetLemmatizer


# # instantiating the lemmaztizer object
# lemmatizer = WordNetLemmatizer()

# # lemmatizing each word through a list comprehension
# test_clean['message'] = [lemmatizer.lemmatize(token) for token in test_clean['message']]

In [18]:
# from nltk.corpus import stopwords
# nltk.download('stopwords')
# stop_words = stopwords.words('english')
# test_clean['message'] = test_clean['message'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [19]:
# test_clean

In [20]:
test_clean = df_test['message'].values.tolist()

In [21]:
#Run the model on test data
predictions, raw_outputs = model.predict(test_clean)

  0%|          | 0/2906 [00:00<?, ?it/s]

  0%|          | 0/364 [00:00<?, ?it/s]

In [22]:
predictions = class_le.inverse_transform(predictions)

In [23]:
my_submission = pd.DataFrame({'id': df_test.id, 'predicted': predictions})

In [24]:
my_submission

id             predicted
0     12123  reportbrokensoftware
1       244      orderpizzaintent
2      8221           replacecard
3     12856    startserviceintent
4     12108         expensereport
...     ...                   ...
2901   7124      checkclaimstatus
2902  13534  getinformationintent
2903   1678     orderburgerintent
2904   6154   getproofofinsurance
2905    615      ordersaladintent

[2906 rows x 2 columns]

In [25]:
# NOTE: after saving the CSV file, be sure to zip the file before submitting to the competition website!
my_submission.to_csv('FinalRoberta.csv', index=False)

In [26]:
from google.colab import files
files.download("FinalRoberta.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>